spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eknaij/tensquare_config
  rabbitmq:
    host: 192.168.192.130
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 12000