server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.192.130
aliyun:
  sms:
    accessKeyId: LTAIRnRYq4jwUCxo
    accessKeySecret: IUgFBjclOSQzWMfsFsCNLMmmN9UzRa
    template_code: SMS_168310959
    sign_name: eknaij
